! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ozone_StoichiomSP.f90
! Time                 : Sun Sep 25 18:07:20 2016
! Working directory    : /home/pzzhou/Scripts/Fortran/SOSAA/Tools/kpp_ozone/Chemistry
! Equation file        : ozone.kpp
! Output root filename : ozone
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ozone_StoichiomSP

  USE ozone_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(5) :: CROW_JVRP = (/ &
       1,  2,  4,  4,  5 /)

  INTEGER, PARAMETER, DIMENSION(4) :: ICOL_JVRP = (/ &
       1,  1,  2,  2 /)

  INTEGER, PARAMETER, DIMENSION(4) :: IROW_JVRP = (/ &
       1,  2,  2,  4 /)



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(5) :: CCOL_STOICM = (/ &
       1,  3,  5,  6,  8 /)

  INTEGER, PARAMETER, DIMENSION(7) :: IROW_STOICM = (/ &
       1,  2,  1,  2,  1,  1,  2 /)

  INTEGER, PARAMETER, DIMENSION(7) :: ICOL_STOICM = (/ &
       1,  1,  2,  2,  3,  4,  4 /)

  REAL(kind=dp), PARAMETER, DIMENSION(7) :: STOICM = (/ &
       -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  2.000000e+00_dp, &
       1.000000e+00_dp,  -1.000000e+00_dp /)


END MODULE ozone_StoichiomSP

