! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ozone_JacobianSP.f90
! Time                 : Sun Sep 25 18:07:20 2016
! Working directory    : /home/pzzhou/Scripts/Fortran/SOSAA/Tools/kpp_ozone/Chemistry
! Equation file        : ozone.kpp
! Output root filename : ozone
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ozone_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(4) :: LU_IROW = (/ &
       1,  1,  2,  2 /)

  INTEGER, PARAMETER, DIMENSION(4) :: LU_ICOL = (/ &
       1,  2,  1,  2 /)

  INTEGER, PARAMETER, DIMENSION(3) :: LU_CROW = (/ &
       1,  3,  5 /)

  INTEGER, PARAMETER, DIMENSION(3) :: LU_DIAG = (/ &
       1,  4,  5 /)


END MODULE ozone_JacobianSP

