! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ozone_Monitor.f90
! Time                 : Sun Sep 25 18:07:20 2016
! Working directory    : /home/pzzhou/Scripts/Fortran/SOSAA/Tools/kpp_ozone/Chemistry
! Equation file        : ozone.kpp
! Output root filename : ozone
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ozone_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(3) :: SPC_NAMES = (/ &
     'O              ','O3             ','dummy_O2       ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(4) :: EQN_NAMES = (/ &
     'O + dummy_O2 --> O3                                                                                 ', &
     '      O + O3 --> dummy_O2                                                                           ', &
     '    dummy_O2 --> 2 O                                                                                ', &
     '          O3 --> O + dummy_O2                                                                       ' /)

! INLINED global variables

! End INLINED global variables


END MODULE ozone_Monitor
