! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Hessian Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : ozone_HessianSP.f90
! Time                 : Sun Sep 25 18:07:20 2016
! Working directory    : /home/pzzhou/Scripts/Fortran/SOSAA/Tools/kpp_ozone/Chemistry
! Equation file        : ozone.kpp
! Output root filename : ozone
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE ozone_HessianSP

  PUBLIC
  SAVE


! Hessian Sparse Data
! 

  INTEGER, PARAMETER, DIMENSION(2) :: IHESS_I = (/ &
       1,  2 /)

  INTEGER, PARAMETER, DIMENSION(2) :: IHESS_J = (/ &
       1,  1 /)

  INTEGER, PARAMETER, DIMENSION(2) :: IHESS_K = (/ &
       2,  2 /)


END MODULE ozone_HessianSP

