! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iodine_Rates.f90
! Time                 : Tue Apr 24 18:06:11 2018
! Working directory    : /home/local/pzzhou/Documents/Research/Paper/Myself/2016/Iodine/kpp_iodine/CHEMISTRY/iodine
! Equation file        : iodine.kpp
! Output root filename : iodine
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE iodine_Rates

  USE iodine_Parameters
  USE iodine_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE iodine_Parameters
      !USE iodine_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = (5.60d-34*O2*N2*((TEMP/300)**(-2.6d0))+6.00d-34*O2*O2*((TEMP/300)**(-2.6d0)))
  RCONST(2) = (3.20d-11*EXP(67.0d0/TEMP)*O2+2.0d-11*EXP(130.0d0/TEMP)*N2)
  RCONST(3) = (1.070d-03*SUN*SUN)
  RCONST(4) = (8.0d-12*EXP(-2060.0d0/TEMP))
  RCONST(5) = (2.28d-10*0.5)
  RCONST(6) = (2.28d-10*0.5)
  RCONST(7) = (2.14d-10)
  RCONST(8) = (4.80d-11*EXP(250.0d0/TEMP))
  RCONST(9) = (2.90d-12*EXP(-160.0d0/TEMP))
  RCONST(10) = (1.70d-12*EXP(-940.0d0/TEMP))
  RCONST(11) = (6.2d-14*(TEMP/298.0d0)**2.6d0*EXP(945.0d0/TEMP))
  RCONST(12) = (4.3d-32*(TEMP/298)**(-1.232d0)*N2+3.1d-32*(TEMP/298.0)**(-1.094)*O2)
  RCONST(13) = (2.4d-11*EXP(100/TEMP))
  RCONST(14) = (2.7d-11*EXP(222/TEMP))
  RCONST(15) = (9.0d-31*(TEMP/300)**(-3.2d0)*N2)
  RCONST(16) = (1.4d-12*EXP(-2000.0d0/TEMP))
  RCONST(17) = (2.9d-12*EXP(-160.0d0/TEMP))
  RCONST(18) = (1.7d-12*EXP(-940.0d0/TEMP))
  RCONST(19) = (2.2d-13*EXP(600.0d0/TEMP))
  RCONST(20) = (2.03d-16*(TEMP/300.0d0)**(4.57d0)*EXP(693/TEMP))
  RCONST(21) = (1.0D-31*(TEMP/300.0)*(-1.6)*N2)
  RCONST(22) = (5.50D-12*EXP(188.0/TEMP))
  RCONST(23) = (1.3d-31*(TEMP/300)**(-1.5)*N2)
  RCONST(24) = (1.7d-11)
  RCONST(25) = (2.5d-12*EXP(260.0/TEMP))
  RCONST(26) = (3.2d-30*(TEMP/300.0)**(-4.5)*N2)
  RCONST(27) = (1.0d-31*(TEMP/300.0)**(-4.5)*N2)
  RCONST(28) = (2.0d-11)
  RCONST(29) = (3.45D-12*EXP(270.0/TEMP))
  RCONST(30) = (1.4D-31*(TEMP/300.0)**(-3.1)*N2)
  RCONST(31) = (1.9D-12)
  RCONST(32) = (2.5D-12)
  RCONST(33) = (2.07D-12*EXP(-1400.0/TEMP))
  RCONST(34) = (3.1d-34*(TEMP/300.0)**(-7.7)*N2)
  RCONST(35) = (1.8d-11*EXP(110.0/TEMP))
  RCONST(36) = (1.4d-33*(TEMP/300.0)**(-3.8)*N2)
  RCONST(37) = (3.6d-30*(TEMP/300.0)**(-4.1)*N2)
  RCONST(38) = (1.25D-10)
  RCONST(39) = (1.4d-10)
  RCONST(40) = (1.5d-11*EXP(-1090.0/TEMP))
  RCONST(41) = (2.1d-11*EXP(-830.0/TEMP))
  RCONST(42) = (1.7d-11)
  RCONST(43) = (3.0d-31*(TEMP/300.0)**(-1)*O2+3.0D-31*(TEMP/300.0)**(-1)*N2)
  RCONST(44) = (1.0d-10)
  RCONST(45) = (1.5d-12)
  RCONST(46) = (1.6d-11*EXP(440.0/TEMP))
  RCONST(47) = (2.1d-10)
  RCONST(48) = (9.0d-12)
  RCONST(49) = (1.4d-11*EXP(540.0/TEMP))
  RCONST(50) = (1.0d-15)
  RCONST(51) = (2.0d-16)
  RCONST(52) = (5.4d-11*EXP(180.0/TEMP)*0.05)
  RCONST(53) = (5.4d-11*EXP(180.0/TEMP)*0.11)
  RCONST(54) = (5.4d-11*EXP(180.0/TEMP)*0.38)
  RCONST(55) = (5.4d-11*EXP(180.0/TEMP)*0.46)
  RCONST(56) = (7.15D-12*EXP(300.0/TEMP))
  RCONST(57) = (7.96D-31*(TEMP/298.0)**(-5.0)*O2+7.96D-31*(TEMP/298.0)**(-5.0)*N2)
  RCONST(58) = (1.3D-14)
  RCONST(59) = (4.7D-13*EXP(-1670.0/TEMP))
  RCONST(60) = (1.1D-12*EXP(542.0/TEMP))
  RCONST(61) = (2.07D-13*(TEMP/298)**2.36*EXP(-5.6d0/R01/TEMP))
  RCONST(62) = (3.72D-16*(TEMP/298)**4.33*EXP(19.0d0/R01/TEMP))
  RCONST(63) = (5.5D-10*EXP(0.36/R01/TEMP))
  RCONST(64) = (K01)
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE iodine_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE iodine_Rates

