! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iodine_Monitor.f90
! Time                 : Tue Apr 24 18:06:11 2018
! Working directory    : /home/local/pzzhou/Documents/Research/Paper/Myself/2016/Iodine/kpp_iodine/CHEMISTRY/iodine
! Equation file        : iodine.kpp
! Output root filename : iodine
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE iodine_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(29) :: SPC_NAMES = (/ &
     'dummy          ','HONO2          ','HO2NO2         ', &
     'N2O3           ','N2O4           ','N2O5           ', &
     'IONO2          ','I2O2           ','HIO3           ', &
     'H              ','HONO           ','INO            ', &
     'INO2           ','O1D            ','H2O2           ', &
     'HOI            ','HI             ','OIO            ', &
     'H2O            ','I2             ','O3             ', &
     'I              ','O              ','NO             ', &
     'NO3            ','OH             ','HO2            ', &
     'IO             ','NO2            ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '        O --> O3                                                                                    ', &
     '      O1D --> O                                                                                     ', &
     '       O3 --> O1D                                                                                   ', &
     '   O3 + O --> dummy                                                                                 ', &
     ' O1D + O3 --> 2 O                                                                                   ', &
     ' O1D + O3 --> dummy                                                                                 ', &
     'O1D + H2O --> 2 OH                                                                                  ', &
     ' OH + HO2 --> H2O                                                                                   ', &
     'H2O2 + OH --> HO2                                                                                   ', &
     '  O3 + OH --> HO2                                                                                   ', &
     '     2 OH --> H2O + O                                                                               ', &
     '        H --> HO2                                                                                   ', &
     '   O + OH --> dummy + H                                                                             ', &
     '  O + HO2 --> OH                                                                                    ', &
     '     2 OH --> H2O2                                                                                  ', &
     ' H2O2 + O --> OH + HO2                                                                              ', &
     'H2O2 + OH --> H2O + HO2                                                                             ', &
     '  O3 + OH --> dummy + HO2                                                                           ', &
     '    2 HO2 --> H2O2                                                                                  ', &
     ' O3 + HO2 --> OH                                                                                    ', &
     '   O + NO --> NO2                                                                                   ', &
     '  O + NO2 --> NO                                                                                    ', &
     '  O + NO2 --> NO3                                                                                   ', &
     '  O + NO3 --> NO2                                                                                   ', &
     'HONO + OH --> H2O + NO2                                                                             ', &
     ' OH + NO2 --> HONO2                                                                                 ', &
     ' OH + NO2 --> dummy                                                                                 ', &
     ' NO3 + OH --> HO2 + NO2                                                                             ', &
     ' NO + HO2 --> OH + NO2                                                                              ', &
     'HO2 + NO2 --> HO2NO2                                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     'NO3 + HO2 --> dummy                                                                                 ', &
     'NO3 + HO2 --> OH + NO2                                                                              ', &
     '  O3 + NO --> NO2                                                                                   ', &
     ' NO + NO2 --> N2O3                                                                                  ', &
     ' NO + NO3 --> 2 NO2                                                                                 ', &
     '    2 NO2 --> N2O4                                                                                  ', &
     'NO3 + NO2 --> N2O5                                                                                  ', &
     '   I2 + O --> I + IO                                                                                ', &
     '   O + IO --> dummy + I                                                                             ', &
     '  I + HO2 --> dummy + HI                                                                            ', &
     '   O3 + I --> dummy + IO                                                                            ', &
     '   I + NO --> INO                                                                                   ', &
     '  I + NO2 --> INO2                                                                                  ', &
     '  I + NO3 --> IO + NO2                                                                              ', &
     ' I2 + NO3 --> IONO2 + I                                                                             ', &
     '  HI + OH --> H2O + I                                                                               ', &
     '  I2 + OH --> HOI + I                                                                               ', &
     ' NO3 + IO --> OIO + NO2                                                                             ', &
     ' HO2 + IO --> dummy + HOI                                                                           ', &
     '  O3 + IO --> dummy + I                                                                             ', &
     '  O3 + IO --> OIO                                                                                   ', &
     '     2 IO --> I2                                                                                    ', &
     '     2 IO --> 2 I                                                                                   ', &
     '     2 IO --> OIO + I                                                                               ', &
     '     2 IO --> I2O2                                                                                  ', &
     '  NO + IO --> I + NO2                                                                               ', &
     ' IO + NO2 --> IONO2                                                                                 ', &
     '    2 INO --> I2 + 2 NO                                                                             ', &
     '   2 INO2 --> I2 + 2 NO2                                                                            ', &
     ' OIO + NO --> IO + NO2                                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(4) :: EQN_NAMES_2 = (/ &
     '  HI + IO --> HOI + I                                                                               ', &
     ' HOI + OH --> H2O + IO                                                                              ', &
     ' OIO + OH --> HIO3                                                                                  ', &
     ' HO2 + IO --> HIO3                                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(64) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2 /)

! INLINED global variables

! End INLINED global variables


END MODULE iodine_Monitor
