! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iodine_Parameters.f90
! Time                 : Tue Apr 24 18:06:10 2018
! Working directory    : /home/local/pzzhou/Documents/Research/Paper/Myself/2016/Iodine/kpp_iodine/CHEMISTRY/iodine
! Equation file        : iodine.kpp
! Output root filename : iodine
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE iodine_Parameters

  USE iodine_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 29 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 29 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 20 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 64 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 30 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 186 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 203 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 30 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_dummy = 1 
  INTEGER, PARAMETER :: ind_HONO2 = 2 
  INTEGER, PARAMETER :: ind_HO2NO2 = 3 
  INTEGER, PARAMETER :: ind_N2O3 = 4 
  INTEGER, PARAMETER :: ind_N2O4 = 5 
  INTEGER, PARAMETER :: ind_N2O5 = 6 
  INTEGER, PARAMETER :: ind_IONO2 = 7 
  INTEGER, PARAMETER :: ind_I2O2 = 8 
  INTEGER, PARAMETER :: ind_HIO3 = 9 
  INTEGER, PARAMETER :: ind_H = 10 
  INTEGER, PARAMETER :: ind_HONO = 11 
  INTEGER, PARAMETER :: ind_INO = 12 
  INTEGER, PARAMETER :: ind_INO2 = 13 
  INTEGER, PARAMETER :: ind_O1D = 14 
  INTEGER, PARAMETER :: ind_H2O2 = 15 
  INTEGER, PARAMETER :: ind_HOI = 16 
  INTEGER, PARAMETER :: ind_HI = 17 
  INTEGER, PARAMETER :: ind_OIO = 18 
  INTEGER, PARAMETER :: ind_H2O = 19 
  INTEGER, PARAMETER :: ind_I2 = 20 
  INTEGER, PARAMETER :: ind_O3 = 21 
  INTEGER, PARAMETER :: ind_I = 22 
  INTEGER, PARAMETER :: ind_O = 23 
  INTEGER, PARAMETER :: ind_NO = 24 
  INTEGER, PARAMETER :: ind_NO3 = 25 
  INTEGER, PARAMETER :: ind_OH = 26 
  INTEGER, PARAMETER :: ind_HO2 = 27 
  INTEGER, PARAMETER :: ind_IO = 28 
  INTEGER, PARAMETER :: ind_NO2 = 29 

! Index declaration for fixed species in C
!   C(ind_spc)


! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)


END MODULE iodine_Parameters

