! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mcm_Function.f90
! Time                 : Thu Jan 24 12:11:47 2019
! Working directory    : /home/local/pzzhou/Scripts/repos/homo/chemistry/mcm
! Equation file        : mcm.kpp
! Output root filename : mcm
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mcm_Function

  USE mcm_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


! Computation of equation rates
  A(1) = RCT(1)*V(39)
  A(2) = RCT(2)*V(39)*V(53)
  A(3) = RCT(3)*V(39)*V(51)
  A(4) = RCT(4)*V(39)*V(54)
  A(5) = RCT(5)*V(39)*V(54)
  A(6) = RCT(6)*V(5)
  A(7) = RCT(7)*V(51)*V(53)
  A(8) = RCT(8)*V(53)*V(54)
  A(9) = RCT(9)*V(51)*V(51)
  A(10) = RCT(10)*V(50)*V(51)
  A(11) = RCT(11)*V(50)*V(54)
  A(12) = RCT(12)*V(50)*V(54)
  A(13) = RCT(13)*V(5)
  A(14) = RCT(14)*V(49)*V(53)
  A(15) = RCT(15)*V(9)*V(49)
  A(16) = RCT(16)*V(22)*V(49)
  A(17) = RCT(17)*V(8)*V(49)
  A(18) = RCT(18)*V(52)*V(53)
  A(19) = RCT(19)*V(49)*V(52)
  A(20) = RCT(20)*V(52)*V(52)
  A(21) = RCT(21)*V(49)*V(51)
  A(22) = RCT(22)*V(49)*V(54)
  A(23) = RCT(23)*V(49)*V(50)
  A(24) = RCT(24)*V(51)*V(52)
  A(25) = RCT(25)*V(52)*V(54)
  A(26) = RCT(26)*V(20)*V(49)
  A(27) = RCT(27)*V(50)*V(52)
  A(28) = RCT(28)*V(14)*V(49)
  A(29) = RCT(29)*V(33)*V(49)
  A(30) = RCT(30)*V(39)*V(47)
  A(31) = RCT(31)*V(47)*V(49)
  A(32) = RCT(32)*V(6)
  A(33) = RCT(33)*V(33)
  A(34) = RCT(34)*V(7)
  A(35) = RCT(35)*V(4)
  A(36) = RCT(36)*V(53)
  A(37) = RCT(37)*V(53)
  A(38) = RCT(38)*V(8)
  A(39) = RCT(39)*V(54)
  A(40) = RCT(40)*V(50)
  A(41) = RCT(41)*V(50)
  A(42) = RCT(42)*V(14)
  A(43) = RCT(43)*V(33)
  A(44) = RCT(44)*V(7)
  A(45) = RCT(45)*V(20)
  A(46) = RCT(46)*V(27)*V(50)
  A(47) = RCT(47)*V(27)*V(49)
  A(48) = RCT(48)*V(27)*V(49)
  A(49) = RCT(49)*V(42)*V(52)
  A(50) = RCT(50)*V(42)*V(51)
  A(51) = RCT(51)*V(42)*V(50)
  A(52) = RCT(52)*V(42)
  A(53) = RCT(53)*V(42)
  A(54) = RCT(54)*V(42)
  A(55) = RCT(55)*V(36)*V(51)
  A(56) = RCT(56)*V(36)
  A(57) = RCT(57)*V(31)*V(49)
  A(58) = RCT(58)*V(31)
  A(59) = RCT(59)*V(17)
  A(60) = RCT(60)*V(13)*V(49)
  A(61) = RCT(61)*V(24)*V(49)
  A(62) = RCT(62)*V(24)
  A(63) = RCT(63)*V(11)*V(49)
  A(64) = RCT(64)*V(15)*V(49)
  A(65) = RCT(65)*V(44)*V(54)
  A(66) = RCT(66)*V(44)*V(53)
  A(67) = RCT(67)*V(44)
  A(68) = RCT(68)*V(41)
  A(69) = RCT(69)*V(41)
  A(70) = RCT(70)*V(41)*V(50)
  A(71) = RCT(71)*V(41)*V(49)
  A(72) = RCT(72)*V(40)*V(52)
  A(73) = RCT(73)*V(40)*V(51)
  A(74) = RCT(74)*V(40)*V(50)
  A(75) = RCT(75)*V(40)
  A(76) = RCT(76)*V(40)
  A(77) = RCT(77)*V(40)
  A(78) = RCT(78)*V(35)*V(49)
  A(79) = RCT(79)*V(45)*V(52)
  A(80) = RCT(80)*V(45)*V(52)
  A(81) = RCT(81)*V(45)*V(51)
  A(82) = RCT(82)*V(45)*V(51)
  A(83) = RCT(83)*V(45)*V(54)
  A(84) = RCT(84)*V(45)*V(50)
  A(85) = RCT(85)*V(45)
  A(86) = RCT(86)*V(45)
  A(87) = RCT(87)*V(45)
  A(88) = RCT(88)*V(43)*V(54)
  A(89) = RCT(89)*V(43)*V(54)
  A(90) = RCT(90)*V(43)*V(53)
  A(91) = RCT(91)*V(43)
  A(92) = RCT(92)*V(37)*V(51)
  A(93) = RCT(93)*V(37)*V(54)
  A(94) = RCT(94)*V(37)
  A(95) = RCT(95)*V(37)
  A(96) = RCT(96)*V(34)*V(49)
  A(97) = RCT(97)*V(34)*V(49)
  A(98) = RCT(98)*V(34)
  A(99) = RCT(99)*V(25)
  A(100) = RCT(100)*V(23)*V(49)
  A(101) = RCT(101)*V(23)
  A(102) = RCT(102)*V(16)*V(49)
  A(103) = RCT(103)*V(16)*V(49)
  A(104) = RCT(104)*V(32)
  A(105) = RCT(105)*V(32)*V(49)
  A(106) = RCT(106)*V(32)*V(49)
  A(107) = RCT(107)*V(30)
  A(108) = RCT(108)*V(30)*V(49)
  A(109) = RCT(109)*V(26)
  A(110) = RCT(110)*V(10)
  A(111) = RCT(111)*V(12)*V(49)
  A(112) = RCT(112)*V(48)*V(53)
  A(113) = RCT(113)*V(48)
  A(114) = RCT(114)*V(48)
  A(115) = RCT(115)*V(52)*V(55)
  A(116) = RCT(116)*V(52)*V(55)
  A(117) = RCT(117)*V(52)*V(55)
  A(118) = RCT(118)*V(51)*V(55)
  A(119) = RCT(119)*V(54)*V(55)
  A(120) = RCT(120)*V(50)*V(55)
  A(121) = RCT(121)*V(55)
  A(122) = RCT(122)*V(55)
  A(123) = RCT(123)*V(55)
  A(124) = RCT(124)*V(38)*V(52)
  A(125) = RCT(125)*V(38)
  A(126) = RCT(126)*V(46)*V(52)
  A(127) = RCT(127)*V(46)*V(52)
  A(128) = RCT(128)*V(46)*V(52)
  A(129) = RCT(129)*V(46)*V(51)
  A(130) = RCT(130)*V(46)*V(54)
  A(131) = RCT(131)*V(46)*V(50)
  A(132) = RCT(132)*V(46)
  A(133) = RCT(133)*V(46)
  A(134) = RCT(134)*V(46)
  A(135) = RCT(135)*V(19)*V(49)
  A(136) = RCT(136)*V(19)
  A(137) = RCT(137)*V(29)*V(49)
  A(138) = RCT(138)*V(29)
  A(139) = RCT(139)*V(18)*V(49)
  A(140) = RCT(140)*V(21)*V(49)
  A(141) = RCT(141)*V(21)
  A(142) = RCT(142)*V(28)*V(49)
  A(143) = RCT(143)*V(28)

! Aggregate function
  Vdot(1) = A(2)+A(19)
  Vdot(2) = A(33)+2*A(34)
  Vdot(3) = A(35)
  Vdot(4) = A(30)+A(32)-A(35)+A(125)
  Vdot(5) = -A(6)-A(13)+A(36)
  Vdot(6) = A(31)-A(32)
  Vdot(7) = A(12)-A(34)-A(44)
  Vdot(8) = -A(17)+A(20)-A(38)
  Vdot(9) = -A(15)+A(69)
  Vdot(10) = A(83)-A(110)
  Vdot(11) = A(55)-A(63)
  Vdot(12) = A(86)-A(111)
  Vdot(13) = A(53)-A(60)
  Vdot(14) = A(21)-A(28)-A(42)
  Vdot(15) = A(56)-A(64)
  Vdot(16) = A(77)-A(102)-A(103)
  Vdot(17) = A(50)+A(51)+A(52)+A(58)-A(59)
  Vdot(18) = A(124)+A(128)+A(134)-A(139)
  Vdot(19) = A(116)-A(135)-A(136)
  Vdot(20) = A(25)-A(26)-A(45)
  Vdot(21) = A(126)-A(140)-A(141)
  Vdot(22) = -A(16)+A(61)+A(62)+A(68)+A(69)+A(70)+A(71)+A(100)+A(101)
  Vdot(23) = A(75)+A(96)-A(100)-A(101)+A(102)
  Vdot(24) = A(54)+A(57)+A(60)-A(61)-A(62)
  Vdot(25) = A(73)+A(74)+A(76)+A(98)-A(99)+A(103)
  Vdot(26) = A(82)+A(84)+A(85)+A(104)+A(107)-A(109)
  Vdot(27) = -A(46)-A(47)-A(48)
  Vdot(28) = A(130)-A(142)-A(143)
  Vdot(29) = A(119)-A(137)-A(138)
  Vdot(30) = A(81)-A(107)-A(108)
  Vdot(31) = A(49)-A(57)-A(58)
  Vdot(32) = A(79)-A(104)-A(105)-A(106)
  Vdot(33) = A(22)-A(29)-A(33)-A(43)+A(46)+A(70)+A(142)
  Vdot(34) = A(72)-A(96)-A(97)-A(98)
  Vdot(35) = A(64)-A(78)+A(117)+A(123)+A(137)
  Vdot(36) = A(48)-A(55)-A(56)
  Vdot(37) = A(67)-A(92)-A(93)-A(94)-A(95)
  Vdot(38) = A(112)-A(124)-A(125)+A(127)+A(129)+A(131)+A(133)+A(139)+A(141)
  Vdot(39) = -A(1)-A(2)-A(3)-A(4)-A(5)+A(6)-A(30)+A(37)+A(39)+A(41)
  Vdot(40) = A(63)-A(72)-A(73)-A(74)-A(75)-A(76)-A(77)+A(97)
  Vdot(41) = A(59)-A(68)-A(69)-A(70)-A(71)+A(80)+A(87)+A(99)+A(106)+A(108)+A(109)+A(111)
  Vdot(42) = A(46)+A(47)-A(49)-A(50)-A(51)-A(52)-A(53)-A(54)
  Vdot(43) = A(65)+A(66)-A(88)-A(89)-A(90)-A(91)+A(92)+A(93)+A(121)
  Vdot(44) = A(59)+A(61)+A(62)-A(65)-A(66)-A(67)+A(95)
  Vdot(45) = A(64)+A(78)-A(79)-A(80)-A(81)-A(82)-A(83)-A(84)-A(85)-A(86)-A(87)+A(88)+A(90)+A(94)+A(105)+A(110)+A(113)&
               &+A(125)
  Vdot(46) = A(114)-A(126)-A(127)-A(128)-A(129)-A(130)-A(131)-A(132)-A(133)-A(134)+A(140)+A(142)+A(143)
  Vdot(47) = -A(30)-A(31)+A(78)+A(88)+A(90)+A(94)+A(113)
  Vdot(48) = A(89)+A(99)+A(100)+A(101)-A(112)-A(113)-A(114)+A(115)+A(118)+A(120)+A(122)+A(132)+A(136)
  Vdot(49) = 2*A(13)-A(14)-A(15)-A(16)-A(17)+A(18)-A(19)-A(21)-A(22)-A(23)+A(24)-A(26)+A(27)-A(28)-A(29)-A(31)+2*A(38)&
               &+A(42)+A(43)-A(47)-A(48)+A(58)-A(60)-A(61)-A(63)-A(64)-A(71)-A(78)-A(97)+A(98)-A(100)-A(102)-A(103)+A(104)&
               &-A(105)-A(108)-A(111)+A(115)+A(127)-A(135)+A(136)-A(137)-A(139)-A(140)+A(141)-A(142)
  Vdot(50) = A(5)+A(8)-A(10)-A(11)-A(12)-A(23)-A(27)+A(29)-A(40)-A(41)+A(44)-A(46)-A(51)-A(70)-A(74)-A(84)+A(93)-A(120)&
               &-A(131)
  Vdot(51) = -A(3)+A(4)-A(7)-2*A(9)-A(10)+A(11)-A(21)-A(24)+A(39)+A(40)+A(42)-A(50)-A(55)+A(65)-A(73)-A(81)-A(82)+A(88)&
               &+A(89)-A(92)-A(118)-A(129)
  Vdot(52) = A(14)+A(15)+A(16)+A(17)-A(18)-A(19)-2*A(20)+A(23)-A(24)-A(25)-A(27)+A(32)+A(45)-A(49)+A(55)+A(56)+A(60)&
               &+A(62)+2*A(68)+A(70)+A(71)-A(72)-A(79)-A(80)+A(101)+A(102)+A(109)+A(111)-A(115)-A(116)-A(117)-A(124)-A(126)&
               &-A(127)-A(128)
  Vdot(53) = A(1)-A(2)-A(7)-A(8)-A(14)-A(18)-A(36)-A(37)-A(66)-A(90)-A(112)+A(117)+A(128)
  Vdot(54) = A(3)-A(4)-A(5)+A(7)-A(8)+2*A(9)+2*A(10)-A(12)-A(22)+A(23)+A(24)-A(25)+A(26)+A(27)+A(28)-A(39)+A(41)+A(43)&
               &+A(44)+A(45)+A(50)+A(51)+A(55)-A(65)+A(73)+A(74)+A(82)-A(83)+A(84)-A(88)-A(89)+A(92)-A(93)+A(107)+A(108)&
               &+A(110)+A(118)-A(119)+A(120)+A(129)-A(130)+A(131)+A(137)+A(138)+A(143)
  Vdot(55) = A(91)-A(115)-A(116)-A(117)-A(118)-A(119)-A(120)-A(121)-A(122)-A(123)+A(135)+A(138)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mcm_Function

