! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mcm_Rates.f90
! Time                 : Thu Jan 24 12:11:47 2019
! Working directory    : /home/local/pzzhou/Scripts/repos/homo/chemistry/mcm
! Equation file        : mcm.kpp
! Output root filename : mcm
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mcm_Rates

  USE mcm_Parameters
  USE mcm_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions



! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE mcm_Parameters
      !USE mcm_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST

 
 ! USE constants
 !end of USE statements 
 !
 ! start of executable statements
 RO2 = & 
 C(ind_CH3SCH2O2) + C(ind_HODMSO2) + C(ind_DMSO2O2) + C(ind_CH3O2) + & 
   C(ind_CH3SOO) + C(ind_CH3SOO2) + C(ind_CH3SO2O2 ) 
 KRO2NO = 2.7D-12*EXP(360/TEMP)
KRO2HO2 = 2.91D-13*EXP(1300/TEMP)
KAPHO2 = 5.2D-13*EXP(980/TEMP)
KAPNO = 7.5D-12*EXP(290/TEMP)
KRO2NO3 = 2.3D-12
KNO3AL = 1.4D-12*EXP(-1860/TEMP)
KDEC = 1.00D+06
KROPRIM = 2.50D-14*EXP(-300/TEMP)
KROSEC = 2.50D-14*EXP(-300/TEMP)
KCH3O2 = 1.03D-13*EXP(365/TEMP)
K298CH3O2 = 3.5D-13
K14ISOM1 = 3.00D7*EXP(-5300/TEMP)
KD0 = 1.10D-05*M*EXP(-10100/TEMP)
KDI = 1.90D17*EXP(-14100/TEMP)
KRD = KD0/KDI
FCD = 0.30
NCD = 0.75-1.27*(LOG10(FCD))
FD = 10**(LOG10(FCD)/(1+(LOG10(KRD)/NCD)**2))
KBPAN = (KD0*KDI)*FD/(KD0+KDI)
KC0 = 3.28D-28*M*(TEMP/300)**-6.87
KCI = 1.125D-11*(TEMP/300)**-1.105
KRC = KC0/KCI
FCC = 0.30
NC = 0.75-1.27*(LOG10(FCC))
FC = 10**(LOG10(FCC)/(1+(LOG10(KRC)/NC)**2))
KFPAN = (KC0*KCI)*FC/(KC0+KCI)
K10 = 1.0D-31*M*(TEMP/300)**-1.6
K1I = 5.0D-11*(TEMP/300)**-0.3
KR1 = K10/K1I
FC1 = 0.85
NC1 = 0.75-1.27*(LOG10(FC1))
F1 = 10**(LOG10(FC1)/(1+(LOG10(KR1)/NC1)**2))
KMT01 = (K10*K1I)*F1/(K10+K1I)
K20 = 1.3D-31*M*(TEMP/300)**-1.5
K2I = 2.3D-11*(TEMP/300)**0.24
KR2 = K20/K2I
FC2 = 0.6
NC2 = 0.75-1.27*(LOG10(FC2))
F2 = 10**(LOG10(FC2)/(1+(LOG10(KR2)/NC2)**2))
KMT02 = (K20*K2I)*F2/(K20+K2I)
K30 = 3.6D-30*M*(TEMP/300)**-4.1
K3I = 1.9D-12*(TEMP/300)**0.2
KR3 = K30/K3I
FC3 = 0.35
NC3 = 0.75-1.27*(LOG10(FC3))
F3 = 10**(LOG10(FC3)/(1+(LOG10(KR3)/NC3)**2))
KMT03 = (K30*K3I)*F3/(K30+K3I)
K40 = 1.3D-3*M*(TEMP/300)**-3.5*EXP(-11000/TEMP)
K4I = 9.7D+14*(TEMP/300)**0.1*EXP(-11080/TEMP)
KR4 = K40/K4I
FC4 = 0.35
NC4 = 0.75-1.27*(LOG10(FC4))
F4 = 10**(LOG10(FC4)/(1+(LOG10(KR4)/NC4)**2))
KMT04 = (K40*K4I)*F4/(K40+K4I)
KMT05 = 1.44D-13*(1+(M/4.2D+19))
KMT06 = 1 + (1.40D-21*EXP(2200/TEMP)*H2O)
K70 = 7.4D-31*M*(TEMP/300)**-2.4
K7I = 3.3D-11*(TEMP/300)**-0.3
KR7 = K70/K7I
FC7 = 0.81
NC7 = 0.75-1.27*(LOG10(FC7))
F7 = 10**(LOG10(FC7)/(1+(LOG10(KR7)/NC7)**2))
KMT07 = (K70*K7I)*F7/(K70+K7I)
K80 = 3.2D-30*M*(TEMP/300)**-4.5
K8I = 3.0D-11
KR8 = K80/K8I
FC8 = 0.41
NC8 = 0.75-1.27*(LOG10(FC8))
F8 = 10**(LOG10(FC8)/(1+(LOG10(KR8)/NC8)**2))
KMT08 = (K80*K8I)*F8/(K80+K8I)
K90 = 1.4D-31*M*(TEMP/300)**-3.1
K9I = 4.0D-12
KR9 = K90/K9I
FC9 = 0.4
NC9 = 0.75-1.27*(LOG10(FC9))
F9 = 10**(LOG10(FC9)/(1+(LOG10(KR9)/NC9)**2))
KMT09 = (K90*K9I)*F9/(K90+K9I)
K100 = 4.10D-05*M*EXP(-10650/TEMP)
K10I = 6.0D+15*EXP(-11170/TEMP)
KR10 = K100/K10I
FC10 = 0.4
NC10 = 0.75-1.27*(LOG10(FC10))
F10 = 10**(LOG10(FC10)/(1+(LOG10(KR10)/NC10)**2))
KMT10 = (K100*K10I)*F10/(K100+K10I)
K1 = 2.40D-14*EXP(460/TEMP)
K3 = 6.50D-34*EXP(1335/TEMP)
K4 = 2.70D-17*EXP(2199/TEMP)
K2 = (K3*M)/(1+(K3*M/K4))
KMT11 = K1 + K2
K120 = 2.5D-31*M*(TEMP/300)**-2.6
K12I = 2.0D-12
KR12 = K120/K12I
FC12 = 0.53
NC12 = 0.75-1.27*(LOG10(FC12))
F12 = 10**(LOG10(FC12)/(1.0+(LOG10(KR12)/NC12)**2))
KMT12 = (K120*K12I*F12)/(K120+K12I)
K130 = 2.5D-30*M*(TEMP/300)**-5.5
K13I = 1.8D-11
KR13 = K130/K13I
FC13 = 0.36
NC13 = 0.75-1.27*(LOG10(FC13))
F13 = 10**(LOG10(FC13)/(1+(LOG10(KR13)/NC13)**2))
KMT13 = (K130*K13I)*F13/(K130+K13I)
K140 = 9.0D-5*EXP(-9690/TEMP)*M
K14I = 1.1D+16*EXP(-10560/TEMP)
KR14 = K140/K14I
FC14 = 0.36
NC14 = 0.75-1.27*(LOG10(FC14))
F14 = 10**(LOG10(FC14)/(1+(LOG10(KR14)/NC14)**2))
KMT14 = (K140*K14I)*F14/(K140+K14I)
K150 = 8.6D-29*M*(TEMP/300)**-3.1
K15I = 9.0D-12*(TEMP/300)**-0.85
KR15 = K150/K15I
FC15 = 0.48
NC15 = 0.75-1.27*(LOG10(FC15))
F15 = 10**(LOG10(FC15)/(1+(LOG10(KR15)/NC15)**2))
KMT15 = (K150*K15I)*F15/(K150+K15I)
K160 = 8D-27*M*(TEMP/300)**-3.5
K16I = 3.0D-11*(TEMP/300)**-1
KR16 = K160/K16I
FC16 = 0.5
NC16 = 0.75-1.27*(LOG10(FC16))
F16 = 10**(LOG10(FC16)/(1+(LOG10(KR16)/NC16)**2))
KMT16 = (K160*K16I)*F16/(K160+K16I)
K170 = 5.0D-30*M*(TEMP/300)**-1.5
K17I = 1.0D-12
KR17 = K170/K17I
FC17 = 0.17*EXP(-51/TEMP)+EXP(-TEMP/204)
NC17 = 0.75-1.27*(LOG10(FC17))
F17 = 10**(LOG10(FC17)/(1.0+(LOG10(KR17)/NC17)**2))
KMT17 = (K170*K17I*F17)/(K170+K17I)
KMT18 = 9.5D-39*O2*EXP(5270/TEMP)/(1+7.5D-29*O2*EXP(5610/TEMP))
KPPN0 = 1.7D-03*EXP(-11280/TEMP)*M
KPPNI = 8.3D+16*EXP(-13940/TEMP)
KRPPN = KPPN0/KPPNI
FCPPN = 0.36
NCPPN = 0.75-1.27*(LOG10(FCPPN))
FPPN = 10**(LOG10(FCPPN)/(1+(LOG10(KRPPN)/NCPPN)**2))
KBPPN = (KPPN0*KPPNI)*FCPPN/(KPPN0+KPPNI)
! CALL mcm_constants(time, temp, M, N2, O2, RO2, H2O) 
 

! End INLINED RCONST

  RCONST(1) = (5.6D-34*N2*(TEMP/300)**-2.6*O2+6.0D-34*O2*(TEMP/300)**-2.6*O2)
  RCONST(2) = (8.0D-12*EXP(-2060/TEMP))
  RCONST(3) = (KMT01)
  RCONST(4) = (5.5D-12*EXP(188/TEMP))
  RCONST(5) = (KMT02)
  RCONST(6) = (3.2D-11*EXP(67/TEMP)*O2+2.0D-11*EXP(130/TEMP)*N2)
  RCONST(7) = (1.4D-12*EXP(-1310/TEMP))
  RCONST(8) = (1.4D-13*EXP(-2470/TEMP))
  RCONST(9) = (3.3D-39*EXP(530/TEMP)*O2)
  RCONST(10) = (1.8D-11*EXP(110/TEMP))
  RCONST(11) = (4.50D-14*EXP(-1260/TEMP))
  RCONST(12) = (KMT03)
  RCONST(13) = (2.14D-10*H2O)
  RCONST(14) = (1.70D-12*EXP(-940/TEMP))
  RCONST(15) = (7.7D-12*EXP(-2100/TEMP))
  RCONST(16) = (KMT05)
  RCONST(17) = (2.9D-12*EXP(-160/TEMP))
  RCONST(18) = (2.03D-16*(TEMP/300)**4.57*EXP(693/TEMP))
  RCONST(19) = (4.8D-11*EXP(250/TEMP))
  RCONST(20) = (2.20D-13*KMT06*EXP(600/TEMP)+1.90D-33*M*KMT06*EXP(980/TEMP))
  RCONST(21) = (KMT07)
  RCONST(22) = (KMT08)
  RCONST(23) = (2.0D-11)
  RCONST(24) = (3.45D-12*EXP(270/TEMP))
  RCONST(25) = (KMT09)
  RCONST(26) = (3.2D-13*EXP(690/TEMP)*1.0)
  RCONST(27) = (4.0D-12)
  RCONST(28) = (2.5D-12*EXP(260/TEMP))
  RCONST(29) = (KMT11)
  RCONST(30) = (4.0D-32*EXP(-1000/TEMP)*M)
  RCONST(31) = (KMT12)
  RCONST(32) = (1.3D-12*EXP(-330/TEMP)*O2)
  RCONST(33) = (6.00D-06)
  RCONST(34) = (4.00D-04)
  RCONST(35) = (1.20D-15*H2O)
  RCONST(36) = (J(1))
  RCONST(37) = (J(2))
  RCONST(38) = (J(3))
  RCONST(39) = (J(4))
  RCONST(40) = (J(5))
  RCONST(41) = (J(6))
  RCONST(42) = (J(7))
  RCONST(43) = (J(8))
  RCONST(44) = (KMT04)
  RCONST(45) = (KMT10)
  RCONST(46) = (1.9D-13*EXP(520/TEMP))
  RCONST(47) = (1.12D-11*EXP(-250/TEMP))
  RCONST(48) = (KMT18)
  RCONST(49) = (KRO2HO2*0.387)
  RCONST(50) = (4.9D-12*EXP(260/TEMP))
  RCONST(51) = (KRO2NO3)
  RCONST(52) = (2*(K298CH3O2*1.0D-11)**0.5*RO2*0.8)
  RCONST(53) = (2*(K298CH3O2*1.0D-11)**0.5*RO2*0.1)
  RCONST(54) = (2*(K298CH3O2*1.0D-11)**0.5*RO2*0.1)
  RCONST(55) = (KRO2NO)
  RCONST(56) = (8.90D+10*EXP(-6040/TEMP))
  RCONST(57) = (7.03D-11)
  RCONST(58) = (J(41))
  RCONST(59) = (KDEC)
  RCONST(60) = (2.78D-11)
  RCONST(61) = (1.11D-11)
  RCONST(62) = (J(15))
  RCONST(63) = (4.40D-14)
  RCONST(64) = (6.10D-12*EXP(800/TEMP))
  RCONST(65) = (6.00D-11*EXP(240/TEMP))
  RCONST(66) = (1.15D-12*EXP(430/TEMP))
  RCONST(67) = (1.20D-16*EXP(1580/TEMP)*O2)
  RCONST(68) = (J(11))
  RCONST(69) = (J(12))
  RCONST(70) = (5.5D-16)
  RCONST(71) = (5.4D-12*EXP(135/TEMP))
  RCONST(72) = (KRO2HO2*0.387)
  RCONST(73) = (KRO2NO)
  RCONST(74) = (KRO2NO3)
  RCONST(75) = (2.00D-12*RO2*0.2)
  RCONST(76) = (2.00D-12*RO2*0.6)
  RCONST(77) = (2.00D-12*RO2*0.2)
  RCONST(78) = (9.00D-11)
  RCONST(79) = (3.8D-13*EXP(780/TEMP)*(1-1/(1+498*EXP(-1160/TEMP))))
  RCONST(80) = (3.8D-13*EXP(780/TEMP)*(1/(1+498*EXP(-1160/TEMP))))
  RCONST(81) = (2.3D-12*EXP(360/TEMP)*0.001)
  RCONST(82) = (2.3D-12*EXP(360/TEMP)*0.999)
  RCONST(83) = (KMT13)
  RCONST(84) = (1.2D-12)
  RCONST(85) = (2*KCH3O2*RO2*7.18*EXP(-885/TEMP))
  RCONST(86) = (2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)))
  RCONST(87) = (2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)))
  RCONST(88) = (1.20D-11*0.25)
  RCONST(89) = (1.20D-11*0.75)
  RCONST(90) = (4.00D-13)
  RCONST(91) = (3.12D-16*EXP(1580/TEMP)*O2)
  RCONST(92) = (1.1D-11)
  RCONST(93) = (2.2D-11)
  RCONST(94) = (5.60D+16*EXP(-10870/TEMP))
  RCONST(95) = (3.50D+10*EXP(-3560/TEMP))
  RCONST(96) = (1.26D-12)
  RCONST(97) = (3.60D-12)
  RCONST(98) = (J(41))
  RCONST(99) = (KDEC)
  RCONST(100) = (1.78D-12)
  RCONST(101) = (J(15))
  RCONST(102) = (5.23D-13)
  RCONST(103) = (1.40D-13)
  RCONST(104) = (J(41))
  RCONST(105) = (5.3D-12*EXP(190/TEMP)*0.6)
  RCONST(106) = (5.3D-12*EXP(190/TEMP)*0.4)
  RCONST(107) = (J(51))
  RCONST(108) = (4.0D-13*EXP(-845/TEMP))
  RCONST(109) = (7.2D-14*EXP(-1080/TEMP)*O2)
  RCONST(110) = (KMT14)
  RCONST(111) = (2.85D-12*EXP(-345/TEMP))
  RCONST(112) = (3.00D-13)
  RCONST(113) = (5.00D+13*EXP(-9673/TEMP))
  RCONST(114) = (1.03D-16*EXP(1580/TEMP)*O2)
  RCONST(115) = (KAPHO2*0.44)
  RCONST(116) = (KAPHO2*0.41)
  RCONST(117) = (KAPHO2*0.15)
  RCONST(118) = (1.00D-11)
  RCONST(119) = (1.20D-12*(TEMP/300)**-0.9)
  RCONST(120) = (KRO2NO3*1.74)
  RCONST(121) = (9.10D+10*EXP(-3560/TEMP))
  RCONST(122) = (1.00D-11*RO2*0.7)
  RCONST(123) = (1.00D-11*RO2*0.3)
  RCONST(124) = (5.00D-11)
  RCONST(125) = (5.00D+13*EXP(-9946/TEMP))
  RCONST(126) = (KAPHO2*0.41)
  RCONST(127) = (KAPHO2*0.44)
  RCONST(128) = (KAPHO2*0.15)
  RCONST(129) = (1.00D-11)
  RCONST(130) = (1.20D-12*(TEMP/300)**-0.9)
  RCONST(131) = (KRO2NO3*1.74)
  RCONST(132) = (3.01D+10*EXP(-3560/TEMP))
  RCONST(133) = (1.00D-11*RO2*0.7)
  RCONST(134) = (1.00D-11*RO2*0.3)
  RCONST(135) = (9.00D-11)
  RCONST(136) = (J(41))
  RCONST(137) = (1.00D-11)
  RCONST(138) = (5.40D+16*EXP(-13112/TEMP))
  RCONST(139) = (2.24D-14)
  RCONST(140) = (3.60D-12)
  RCONST(141) = (J(41))
  RCONST(142) = (3.60D-13)
  RCONST(143) = (5.40D+16*EXP(-13112/TEMP))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE mcm_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE mcm_Rates

