! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mcm_Parameters.f90
! Time                 : Thu Jan 24 12:11:47 2019
! Working directory    : /home/local/pzzhou/Scripts/repos/homo/chemistry/mcm
! Equation file        : mcm.kpp
! Output root filename : mcm
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mcm_Parameters

  USE mcm_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 55 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 55 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 52 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 143 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 56 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 389 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 441 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 56 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_dummy = 1 
  INTEGER, PARAMETER :: ind_NA = 2 
  INTEGER, PARAMETER :: ind_SA = 3 
  INTEGER, PARAMETER :: ind_SO3 = 4 
  INTEGER, PARAMETER :: ind_O1D = 5 
  INTEGER, PARAMETER :: ind_HSO3 = 6 
  INTEGER, PARAMETER :: ind_N2O5 = 7 
  INTEGER, PARAMETER :: ind_H2O2 = 8 
  INTEGER, PARAMETER :: ind_H2 = 9 
  INTEGER, PARAMETER :: ind_CH3O2NO2 = 10 
  INTEGER, PARAMETER :: ind_DMSO2 = 11 
  INTEGER, PARAMETER :: ind_CH3OH = 12 
  INTEGER, PARAMETER :: ind_CH3SCH2OH = 13 
  INTEGER, PARAMETER :: ind_HONO = 14 
  INTEGER, PARAMETER :: ind_DMSO = 15 
  INTEGER, PARAMETER :: ind_DMSO2OH = 16 
  INTEGER, PARAMETER :: ind_CH3SCH2O = 17 
  INTEGER, PARAMETER :: ind_MSA = 18 
  INTEGER, PARAMETER :: ind_CH3SOOOH = 19 
  INTEGER, PARAMETER :: ind_HO2NO2 = 20 
  INTEGER, PARAMETER :: ind_CH3SO2OOH = 21 
  INTEGER, PARAMETER :: ind_CO = 22 
  INTEGER, PARAMETER :: ind_CH3SO2CHO = 23 
  INTEGER, PARAMETER :: ind_CH3SCHO = 24 
  INTEGER, PARAMETER :: ind_DMSO2O = 25 
  INTEGER, PARAMETER :: ind_CH3O = 26 
  INTEGER, PARAMETER :: ind_DMS = 27 
  INTEGER, PARAMETER :: ind_CH3SO4NO2 = 28 
  INTEGER, PARAMETER :: ind_CH3SOO2NO2 = 29 
  INTEGER, PARAMETER :: ind_CH3NO3 = 30 
  INTEGER, PARAMETER :: ind_CH3SCH2OOH = 31 
  INTEGER, PARAMETER :: ind_CH3OOH = 32 
  INTEGER, PARAMETER :: ind_HNO3 = 33 
  INTEGER, PARAMETER :: ind_DMSO2OOH = 34 
  INTEGER, PARAMETER :: ind_MSIA = 35 
  INTEGER, PARAMETER :: ind_HODMSO2 = 36 
  INTEGER, PARAMETER :: ind_CH3SOO = 37 
  INTEGER, PARAMETER :: ind_CH3SO3 = 38 
  INTEGER, PARAMETER :: ind_O = 39 
  INTEGER, PARAMETER :: ind_DMSO2O2 = 40 
  INTEGER, PARAMETER :: ind_HCHO = 41 
  INTEGER, PARAMETER :: ind_CH3SCH2O2 = 42 
  INTEGER, PARAMETER :: ind_CH3SO = 43 
  INTEGER, PARAMETER :: ind_CH3S = 44 
  INTEGER, PARAMETER :: ind_CH3O2 = 45 
  INTEGER, PARAMETER :: ind_CH3SO2O2 = 46 
  INTEGER, PARAMETER :: ind_SO2 = 47 
  INTEGER, PARAMETER :: ind_CH3SO2 = 48 
  INTEGER, PARAMETER :: ind_OH = 49 
  INTEGER, PARAMETER :: ind_NO3 = 50 
  INTEGER, PARAMETER :: ind_NO = 51 
  INTEGER, PARAMETER :: ind_HO2 = 52 
  INTEGER, PARAMETER :: ind_O3 = 53 
  INTEGER, PARAMETER :: ind_NO2 = 54 
  INTEGER, PARAMETER :: ind_CH3SOO2 = 55 

! Index declaration for fixed species in C
!   C(ind_spc)


! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)


END MODULE mcm_Parameters

