! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mcm_Monitor.f90
! Time                 : Thu Jan 24 12:11:47 2019
! Working directory    : /home/local/pzzhou/Scripts/repos/homo/chemistry/mcm
! Equation file        : mcm.kpp
! Output root filename : mcm
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mcm_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(55) :: SPC_NAMES = (/ &
     'dummy          ','NA             ','SA             ', &
     'SO3            ','O1D            ','HSO3           ', &
     'N2O5           ','H2O2           ','H2             ', &
     'CH3O2NO2       ','DMSO2          ','CH3OH          ', &
     'CH3SCH2OH      ','HONO           ','DMSO           ', &
     'DMSO2OH        ','CH3SCH2O       ','MSA            ', &
     'CH3SOOOH       ','HO2NO2         ','CH3SO2OOH      ', &
     'CO             ','CH3SO2CHO      ','CH3SCHO        ', &
     'DMSO2O         ','CH3O           ','DMS            ', &
     'CH3SO4NO2      ','CH3SOO2NO2     ','CH3NO3         ', &
     'CH3SCH2OOH     ','CH3OOH         ','HNO3           ', &
     'DMSO2OOH       ','MSIA           ','HODMSO2        ', &
     'CH3SOO         ','CH3SO3         ','O              ', &
     'DMSO2O2        ','HCHO           ','CH3SCH2O2      ', &
     'CH3SO          ','CH3S           ','CH3O2          ', &
     'CH3SO2O2       ','SO2            ','CH3SO2         ', &
     'OH             ','NO3            ','NO             ', &
     'HO2            ','O3             ','NO2            ', &
     'CH3SOO2        ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '              O --> O3                                                                              ', &
     '         O + O3 --> dummy                                                                           ', &
     '         O + NO --> NO2                                                                             ', &
     '        O + NO2 --> NO                                                                              ', &
     '        O + NO2 --> NO3                                                                             ', &
     '            O1D --> O                                                                               ', &
     '        NO + O3 --> NO2                                                                             ', &
     '       O3 + NO2 --> NO3                                                                             ', &
     '           2 NO --> 2 NO2                                                                           ', &
     '       NO3 + NO --> 2 NO2                                                                           ', &
     '      NO3 + NO2 --> NO + NO2                                                                        ', &
     '      NO3 + NO2 --> N2O5                                                                            ', &
     '            O1D --> 2 OH                                                                            ', &
     '        OH + O3 --> HO2                                                                             ', &
     '        H2 + OH --> HO2                                                                             ', &
     '        CO + OH --> HO2                                                                             ', &
     '      H2O2 + OH --> HO2                                                                             ', &
     '       HO2 + O3 --> OH                                                                              ', &
     '       OH + HO2 --> dummy                                                                           ', &
     '          2 HO2 --> H2O2                                                                            ', &
     '        OH + NO --> HONO                                                                            ', &
     '       OH + NO2 --> HNO3                                                                            ', &
     '       OH + NO3 --> HO2 + NO2                                                                       ', &
     '       NO + HO2 --> OH + NO2                                                                        ', &
     '      HO2 + NO2 --> HO2NO2                                                                          ', &
     '    HO2NO2 + OH --> NO2                                                                             ', &
     '      NO3 + HO2 --> OH + NO2                                                                        ', &
     '      HONO + OH --> NO2                                                                             ', &
     '      HNO3 + OH --> NO3                                                                             ', &
     '        O + SO2 --> SO3                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '       SO2 + OH --> HSO3                                                                            ', &
     '           HSO3 --> SO3 + HO2                                                                       ', &
     '           HNO3 --> NA                                                                              ', &
     '           N2O5 --> 2 NA                                                                            ', &
     '            SO3 --> SA                                                                              ', &
     '             O3 --> O1D                                                                             ', &
     '             O3 --> O                                                                               ', &
     '           H2O2 --> 2 OH                                                                            ', &
     '            NO2 --> O + NO                                                                          ', &
     '            NO3 --> NO                                                                              ', &
     '            NO3 --> O + NO2                                                                         ', &
     '           HONO --> OH + NO                                                                         ', &
     '           HNO3 --> OH + NO2                                                                        ', &
     '           N2O5 --> NO3 + NO2                                                                       ', &
     '         HO2NO2 --> HO2 + NO2                                                                       ', &
     '      DMS + NO3 --> HNO3 + CH3SCH2O2                                                                ', &
     '       DMS + OH --> CH3SCH2O2                                                                       ', &
     '       DMS + OH --> HODMSO2                                                                         ', &
     'CH3SCH2O2 + HO2 --> CH3SCH2OOH                                                                      ', &
     ' CH3SCH2O2 + NO --> CH3SCH2O + NO2                                                                  ', &
     'CH3SCH2O2 + NO3 --> CH3SCH2O + NO2                                                                  ', &
     '      CH3SCH2O2 --> CH3SCH2O                                                                        ', &
     '      CH3SCH2O2 --> CH3SCH2OH                                                                       ', &
     '      CH3SCH2O2 --> CH3SCHO                                                                         ', &
     '   HODMSO2 + NO --> DMSO2 + HO2 + NO2                                                               ', &
     '        HODMSO2 --> DMSO + HO2                                                                      ', &
     'CH3SCH2OOH + OH --> CH3SCHO + OH                                                                    ', &
     '     CH3SCH2OOH --> CH3SCH2O + OH                                                                   ', &
     '       CH3SCH2O --> HCHO + CH3S                                                                     ', &
     ' CH3SCH2OH + OH --> CH3SCHO + HO2                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '   CH3SCHO + OH --> CO + CH3S                                                                       ', &
     '        CH3SCHO --> CO + CH3S + HO2                                                                 ', &
     '     DMSO2 + OH --> DMSO2O2                                                                         ', &
     '      DMSO + OH --> MSIA + CH3O2                                                                    ', &
     '     CH3S + NO2 --> CH3SO + NO                                                                      ', &
     '      CH3S + O3 --> CH3SO                                                                           ', &
     '           CH3S --> CH3SOO                                                                          ', &
     '           HCHO --> CO + 2 HO2                                                                      ', &
     '           HCHO --> H2 + CO                                                                         ', &
     '     HCHO + NO3 --> CO + HNO3 + HO2                                                                 ', &
     '      HCHO + OH --> CO + HO2                                                                        ', &
     '  DMSO2O2 + HO2 --> DMSO2OOH                                                                        ', &
     '   DMSO2O2 + NO --> DMSO2O + NO2                                                                    ', &
     '  DMSO2O2 + NO3 --> DMSO2O + NO2                                                                    ', &
     '        DMSO2O2 --> CH3SO2CHO                                                                       ', &
     '        DMSO2O2 --> DMSO2O                                                                          ', &
     '        DMSO2O2 --> DMSO2OH                                                                         ', &
     '      MSIA + OH --> CH3O2 + SO2                                                                     ', &
     '    CH3O2 + HO2 --> CH3OOH                                                                          ', &
     '    CH3O2 + HO2 --> HCHO                                                                            ', &
     '     CH3O2 + NO --> CH3NO3                                                                          ', &
     '     CH3O2 + NO --> CH3O + NO2                                                                      ', &
     '    CH3O2 + NO2 --> CH3O2NO2                                                                        ', &
     '    CH3O2 + NO3 --> CH3O + NO2                                                                      ', &
     '          CH3O2 --> CH3O                                                                            ', &
     '          CH3O2 --> CH3OH                                                                           ', &
     '          CH3O2 --> HCHO                                                                            ', &
     '    CH3SO + NO2 --> CH3O2 + SO2 + NO                                                                ', &
     '    CH3SO + NO2 --> CH3SO2 + NO                                                                     ', &
     '     CH3SO + O3 --> CH3O2 + SO2                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '          CH3SO --> CH3SOO2                                                                         ', &
     '    CH3SOO + NO --> CH3SO + NO2                                                                     ', &
     '   CH3SOO + NO2 --> CH3SO + NO3                                                                     ', &
     '         CH3SOO --> CH3O2 + SO2                                                                     ', &
     '         CH3SOO --> CH3S                                                                            ', &
     '  DMSO2OOH + OH --> CH3SO2CHO + OH                                                                  ', &
     '  DMSO2OOH + OH --> DMSO2O2                                                                         ', &
     '       DMSO2OOH --> DMSO2O + OH                                                                     ', &
     '         DMSO2O --> HCHO + CH3SO2                                                                   ', &
     ' CH3SO2CHO + OH --> CO + CH3SO2                                                                     ', &
     '      CH3SO2CHO --> CO + CH3SO2 + HO2                                                               ', &
     '   DMSO2OH + OH --> CH3SO2CHO + HO2                                                                 ', &
     '   DMSO2OH + OH --> DMSO2O                                                                          ', &
     '         CH3OOH --> CH3O + OH                                                                       ', &
     '    CH3OOH + OH --> CH3O2                                                                           ', &
     '    CH3OOH + OH --> HCHO + OH                                                                       ', &
     '         CH3NO3 --> CH3O + NO2                                                                      ', &
     '    CH3NO3 + OH --> HCHO + NO2                                                                      ', &
     '           CH3O --> HCHO + HO2                                                                      ', &
     '       CH3O2NO2 --> CH3O2 + NO2                                                                     ', &
     '     CH3OH + OH --> HCHO + HO2                                                                      ', &
     '    CH3SO2 + O3 --> CH3SO3                                                                          ', &
     '         CH3SO2 --> CH3O2 + SO2                                                                     ', &
     '         CH3SO2 --> CH3SO2O2                                                                        ', &
     '  HO2 + CH3SOO2 --> CH3SO2 + OH                                                                     ', &
     '  HO2 + CH3SOO2 --> CH3SOOOH                                                                        ', &
     '  HO2 + CH3SOO2 --> MSIA + O3                                                                       ', &
     '   NO + CH3SOO2 --> CH3SO2 + NO2                                                                    ', &
     '  NO2 + CH3SOO2 --> CH3SOO2NO2                                                                      ', &
     '  NO3 + CH3SOO2 --> CH3SO2 + NO2                                                                    ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(23) :: EQN_NAMES_4 = (/ &
     '        CH3SOO2 --> CH3SO                                                                           ', &
     '        CH3SOO2 --> CH3SO2                                                                          ', &
     '        CH3SOO2 --> MSIA                                                                            ', &
     '   CH3SO3 + HO2 --> MSA                                                                             ', &
     '         CH3SO3 --> SO3 + CH3O2                                                                     ', &
     ' CH3SO2O2 + HO2 --> CH3SO2OOH                                                                       ', &
     ' CH3SO2O2 + HO2 --> CH3SO3 + OH                                                                     ', &
     ' CH3SO2O2 + HO2 --> MSA + O3                                                                        ', &
     '  CH3SO2O2 + NO --> CH3SO3 + NO2                                                                    ', &
     ' CH3SO2O2 + NO2 --> CH3SO4NO2                                                                       ', &
     ' CH3SO2O2 + NO3 --> CH3SO3 + NO2                                                                    ', &
     '       CH3SO2O2 --> CH3SO2                                                                          ', &
     '       CH3SO2O2 --> CH3SO3                                                                          ', &
     '       CH3SO2O2 --> MSA                                                                             ', &
     '  CH3SOOOH + OH --> CH3SOO2                                                                         ', &
     '       CH3SOOOH --> CH3SO2 + OH                                                                     ', &
     'CH3SOO2NO2 + OH --> MSIA + NO2                                                                      ', &
     '     CH3SOO2NO2 --> NO2 + CH3SOO2                                                                   ', &
     '       MSA + OH --> CH3SO3                                                                          ', &
     ' CH3SO2OOH + OH --> CH3SO2O2                                                                        ', &
     '      CH3SO2OOH --> CH3SO3 + OH                                                                     ', &
     ' CH3SO4NO2 + OH --> HNO3 + CH3SO2O2                                                                 ', &
     '      CH3SO4NO2 --> CH3SO2O2 + NO2                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(143) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4 /)

! INLINED global variables

! End INLINED global variables


END MODULE mcm_Monitor
